//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationBytes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MemoryAndSpeedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MemoryAndSpeedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculationBytes.Resources.MemoryAndSpeedResource", typeof(MemoryAndSpeedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit.
        /// </summary>
        internal static string bit_tyte {
            get {
                return ResourceManager.GetString("bit_tyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string byte_type {
            get {
                return ResourceManager.GetString("byte_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exabit.
        /// </summary>
        internal static string Ebit {
            get {
                return ResourceManager.GetString("Ebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exabyte.
        /// </summary>
        internal static string EByte {
            get {
                return ResourceManager.GetString("EByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabit.
        /// </summary>
        internal static string Gbit {
            get {
                return ResourceManager.GetString("Gbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigabyte.
        /// </summary>
        internal static string GByte {
            get {
                return ResourceManager.GetString("GByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobit.
        /// </summary>
        internal static string Kbit {
            get {
                return ResourceManager.GetString("Kbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilobyte.
        /// </summary>
        internal static string KByte {
            get {
                return ResourceManager.GetString("KByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabit.
        /// </summary>
        internal static string Mbit {
            get {
                return ResourceManager.GetString("Mbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megabyte.
        /// </summary>
        internal static string MByte {
            get {
                return ResourceManager.GetString("MByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petabit.
        /// </summary>
        internal static string Pbit {
            get {
                return ResourceManager.GetString("Pbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petabyte.
        /// </summary>
        internal static string PByte {
            get {
                return ResourceManager.GetString("PByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabit.
        /// </summary>
        internal static string Tbit {
            get {
                return ResourceManager.GetString("Tbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terabyte.
        /// </summary>
        internal static string TByte {
            get {
                return ResourceManager.GetString("TByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte/s.
        /// </summary>
        internal static string type_name_per_sec_Byte {
            get {
                return ResourceManager.GetString("type_name_per_sec_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB/s.
        /// </summary>
        internal static string type_name_per_sec_GB {
            get {
                return ResourceManager.GetString("type_name_per_sec_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB/s.
        /// </summary>
        internal static string type_name_per_sec_KB {
            get {
                return ResourceManager.GetString("type_name_per_sec_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB/s.
        /// </summary>
        internal static string type_name_per_sec_MB {
            get {
                return ResourceManager.GetString("type_name_per_sec_MB", resourceCulture);
            }
        }
    }
}
