//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationBytes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculationBytes.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string _switch {
            get {
                return ResourceManager.GetString("switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string calculate {
            get {
                return ResourceManager.GetString("calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File type and Dowload Speed type.
        /// </summary>
        internal static string choose_file_speed_type {
            get {
                return ResourceManager.GetString("choose_file_speed_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File type.
        /// </summary>
        internal static string choose_file_type {
            get {
                return ResourceManager.GetString("choose_file_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose From type and To type.
        /// </summary>
        internal static string choose_from_to_type {
            get {
                return ResourceManager.GetString("choose_from_to_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose From type.
        /// </summary>
        internal static string choose_from_type {
            get {
                return ResourceManager.GetString("choose_from_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Dowload Speed type.
        /// </summary>
        internal static string choose_speed_type {
            get {
                return ResourceManager.GetString("choose_speed_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose To type.
        /// </summary>
        internal static string choose_to_type {
            get {
                return ResourceManager.GetString("choose_to_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string convert {
            get {
                return ResourceManager.GetString("convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Speed:.
        /// </summary>
        internal static string download_speed {
            get {
                return ResourceManager.GetString("download_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Time:.
        /// </summary>
        internal static string download_time {
            get {
                return ResourceManager.GetString("download_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number.
        /// </summary>
        internal static string enter_number {
            get {
                return ResourceManager.GetString("enter_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As.
        /// </summary>
        internal static string equal {
            get {
                return ResourceManager.GetString("equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size:.
        /// </summary>
        internal static string file_size {
            get {
                return ResourceManager.GetString("file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO TO BED TIMES.
        /// </summary>
        internal static string go_to_bed_time {
            get {
                return ResourceManager.GetString("go_to_bed_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF I GO TO SLEEP NOW....
        /// </summary>
        internal static string go_to_sleep_now {
            get {
                return ResourceManager.GetString("go_to_sleep_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN SHOULD I GET UP ?.
        /// </summary>
        internal static string i_get_up {
            get {
                return ResourceManager.GetString("i_get_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN SHOULD I GO TO BED ?.
        /// </summary>
        internal static string i_go_to_bed {
            get {
                return ResourceManager.GetString("i_go_to_bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Speed:.
        /// </summary>
        internal static string internet_speed {
            get {
                return ResourceManager.GetString("internet_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory size:.
        /// </summary>
        internal static string memory_size {
            get {
                return ResourceManager.GetString("memory_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        internal static string select_type {
            get {
                return ResourceManager.GetString("select_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Format.
        /// </summary>
        internal static string time_format {
            get {
                return ResourceManager.GetString("time_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAKE UP TIMES.
        /// </summary>
        internal static string wakes_up_time {
            get {
                return ResourceManager.GetString("wakes_up_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF I WANT TO WAKE UP AT....
        /// </summary>
        internal static string want_to_wake_up {
            get {
                return ResourceManager.GetString("want_to_wake_up", resourceCulture);
            }
        }
    }
}
